### ISSUE TITLE
Need installation documents

### ISSUE THREAD

**Issue by rafiul** [mukto90/mdc-meta-box#1]
Hello, 
I am little bit confused. How I use this library?  My installation process was:
1. Paste "class.mdc-metabox.php" on \wp-content\themes\twentyfifteen
2. Include example file on "function.php"
Where i missed?

Thanks in advance

**Comment by mukto90** [comment]
What I guess is, you have mistaken while including the library file.
To use `example.php` file as it is now, you need to put both files (`example.php` and `class.mdc-metabox.php`) in same directory.
If you keep library file in a separate directory, you must change the path in `example.php` file.

**Comment by mukto90** [comment]
Hello, did you solve it? should we close this issue?

**Comment by rafiul** [comment]
It's working after  WP fresh installation. Thanks
