### ISSUE TITLE
how I call this meta box ? 

### ISSUE THREAD

**Issue by priyabratary** [mukto90/mdc-meta-box#2]
hi thank you for the great meta box but how I retrieve the data from it ?

like <?php
// Grab the metadata from the database
$text = get_post_meta( get_the_ID(), '_yourprefix_text', true );

// Echo the metadata
echo esc_html( $text );
?>
can you please help ? thank you

**Comment by mukto90** [comment]
Yes, you are right. Please see this- https://github.com/mukto90/mdc-meta-box#how-to-use

**Comment by priyabratary** [comment]
Thanks

**Comment by mukto90** [comment]
Does it help? Should we close the issue?

**Comment by priyabratary** [comment]
yes, sure

**Comment by mukto90** [comment]
Thanks.
